### ISSUE TITLE
I get an error running sportdb new en

### ISSUE THREAD

**Issue by aaraia** [openfootball/eng-england#28]
On Windows 10 + ruby 2.5, i get the below error when calling "sportdb new en"

*** error: undefined method `get_input_stream' for nil:NilClass

Can you help?

Heres the preceeding output...

[info] parsing data in zip 'setups/all' (eng-england-master/setups/all.txt)...
[info] parsing data in zip (league) 'eng-england!/leagues' (eng-england-master/leagues.txt)...
DEPRECATION WARNING: update_attributes! is deprecated and will be removed from Rails 6.1 (please, use update! instead) (called from load at C:/Ruby25-x64/bin/sportdb:23)
DEPRECATION WARNING: update_attributes! is deprecated and will be removed from Rails 6.1 (please, use update! instead) (called from load at C:/Ruby25-x64/bin/sportdb:23)
DEPRECATION WARNING: update_attributes! is deprecated and will be removed from Rails 6.1 (please, use update! instead) (called from load at C:/Ruby25-x64/bin/sportdb:23)
DEPRECATION WARNING: update_attributes! is deprecated and will be removed from Rails 6.1 (please, use update! instead) (called from load at C:/Ruby25-x64/bin/sportdb:23)
[info] parsing data in zip (team) 'eng-england!/clubs/1-premierleague' (eng-england-master/clubs/1-premierleague.txt)...

*** error: undefined method `get_input_stream' for nil:NilClass

**Comment by geraldb** [comment]
Welcome to football.db.  Sorry I'm (re)organizing, that is, trying to make the setup simpler / easier  I will need some more weeks to get it all up-to-date.  Thanks for the patience will things break. For questions and support, please use the forum <https://github.com/openfootball/eng-england#questions-comments>.

**Comment by nickschurch** [comment]
I'm getting exactly this same error!

**Comment by geraldb** [comment]
Sorry nothing new it's still the same answer: Welcome to football.db.  Sorry I'm (re)organizing, that is, trying to make the setup simpler / easier  I will need some more weeks to get it all up-to-date.  Thanks for the patience while things break. For questions and support, please use the forum <https://github.com/openfootball/eng-england#questions-comments>.

**PS:  If you try to fix it, the club setup gets reworked. In the meantime you can use the football.csv datasets, see <https://github.com/footballcsv> that are already up-to-date to the "new" system.**

**Comment by nickschurch** [comment]
Do the csv's also include who scored and when?

**Comment by geraldb** [comment]
For questions and support, please use the forum <https://github.com/openfootball/eng-england#questions-comments>.
